name: Docker Release

on:
  # Trigger the workflow on the new 'v*' tag created
  push:
    tags:
      - "v*"
    branches:
      - "*"
  pull_request:
    branches: [master]
jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: ["scratch", "alpine", "debian"]
        platform: ["linux/amd64", "linux/arm64"]
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ matrix.platform }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_IO_REGISTRY_TOKEN }}

      - name: Set target and tag
        id: build-opts
        run: |
          if [ "${{ matrix.distro }}" = 'scratch' ]; then
            echo ::set-output name=target::''
            echo ::set-output name=latest::latest
            echo ::set-output name=tag::"${GITHUB_REF/refs\/tags\/v/}"
          else
            echo ::set-output name=target::"${{ matrix.distro }}-distro"
            echo ::set-output name=latest::"latest-${{ matrix.distro }}"
            echo ::set-output name=tag::"${GITHUB_REF/refs\/tags\/v/}-${{ matrix.distro }}"
          fi

      - name: Build and push
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          target: ${{ steps.build-opts.outputs.target }}
          tags: |
            hadolint/hadolint:${{ steps.build-opts.outputs.latest }}
            hadolint/hadolint:${{ steps.build-opts.outputs.tag }}
            ghcr.io/hadolint/hadolint:${{ steps.build-opts.outputs.latest }}
            ghcr.io/hadolint/hadolint:${{ steps.build-opts.outputs.tag }}

      - name: Test only (without release)
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          target: ${{ steps.build-opts.outputs.target }}
          tags: |
            hadolint/hadolint:test
